service: nestjs-app

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /getHello
          method: GET

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - '**'

custom:
  esbuild:
    bundle: true
    minify: true
    target: node16
    sourcemap: true
