service: nestjs-app


plugins:
  - serverless-dotenv-plugin
  
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  stage: ${env:ENVIRONMENT, 'dev'}  

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: GET
  getHello:
    handler: dist/main.handler
    events:
      - http:
          path: /getHello
          method: GET

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - '**'

custom:
  esbuild:
    bundle: true
    minify: true
    target: node16
    sourcemap: true
