name: CI/CD to AWS Lambda (Serverless)

on:
  push:
    branches:
      - dev
      - main
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Build NestJS application
        run: npm run build

      - name: Package for AWS Lambda
        run: serverless package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-package
          path: .serverless/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy-package
          path: .serverless/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to AWS Lambda (Dev)
        if: github.ref == 'refs/heads/dev'
        run: serverless deploy --stage dev

      - name: Deploy to AWS Lambda (Qa)
        if: github.ref == 'refs/heads/main'
        run: serverless deploy --stage qa

      - name: Deploy to AWS Lambda (Production)
        if: github.ref == 'refs/heads/main'
        run: serverless deploy --stage prod
