name: CI/CD to AWS Lambda (Serverless)

on:
  push:
    branches:
      - dev
      - qa
      - prod


jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> .env
          echo "STAGE==${{github.ref_name}}" >> .env
          cat .env
          
      - name: Set Environment Variables
        run: |
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> $GITHUB_ENV
          echo "STAGE=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "STAGE is set to: ${{ github.ref_name }}"          
          echo "Using STAGE: $STAGE"
          echo "Using ENVIRONMENT: $ENVIRONMENT"

      - name: Clean and Build NestJS application
        run: |
          rm -rf dist
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to AWS Lambda
        run: |
          echo $ENVIRONMENT
          serverless deploy --stage $ENVIRONMENT
      

      