name: CI/CD to AWS Lambda (Serverless)

on:
  push:
    branches:
      - dev
      - qa
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.7

      - name: Install dependencies
        run: npm install

      - name: 'Create .env file'
        run: |
          touch .env
          echo ENVIRONMENT=${{secrets.ENVIRONMENT}} >> .env
          cat .env

      - name: Set Environment Variables
        run: |
          echo "STAGE=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "Using STAGE: $STAGE"

      - name: Install Serverless v3
        run: npm install -g serverless@3

      - name: Clean and Build NestJS application
        run: |
          rm -rf dist
          npm run build

      - name: Package for AWS Lambda
        run: serverless package --package .serverless-output

      - name: Force Move Package
        run: |
          mkdir -p .serverless-output
          mv .serverless/* .serverless-output/ || echo "No files to move"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: .serverless-output/
          
      - name: Check path
        run: |
          pwd
          ls


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-package
          path: .serverless/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Set Environment Variable
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "Unknown branch: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Determine Deployment Stage
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "STAGE=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "STAGE=qa" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "STAGE=prod" >> $GITHUB_ENV
          else
            echo "Unknown branch: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Deploy to AWS Lambda
        run: serverless deploy --stage $STAGE
